import type { LocalService, LocalServicePlan } from "../detectors/services.js";
import type { ProjectContext } from "../types.js";
import { oneTrailingNewline } from "./format.js";

export function generateDockerComposeYml(
  ctx: ProjectContext,
  plan: LocalServicePlan,
): string {
  const projectSlug = slugProjectName(ctx.name);
  const lines = [
    "# Local development services generated by ready-for-agents.",
    "# Review before use. Do not point this compose file at production data.",
    "",
    `name: ${projectSlug}-local`,
    "",
    "services:",
  ];

  for (const service of plan.services) {
    lines.push(...serviceBlock(projectSlug, service));
  }

  const volumes = plan.services.map(
    (service) => `${projectSlug}_${service.volumeSuffix}`,
  );
  if (volumes.length > 0) {
    lines.push("", "volumes:");
    for (const volume of volumes) {
      lines.push(`  ${volume}:`);
    }
  }

  lines.push("", "# Suggested local environment values:");
  for (const service of plan.services) {
    for (const hint of service.envHints) {
      lines.push(`# - ${hint.replace("<database>", projectSlug)}`);
    }
  }

  if (plan.notes.length > 0) {
    lines.push("", "# Notes:");
    for (const note of plan.notes) {
      lines.push(`# - ${note}`);
    }
  }

  return oneTrailingNewline(lines.join("\n"));
}

function serviceBlock(projectSlug: string, service: LocalService): string[] {
  switch (service.id) {
    case "mongodb":
      return [
        "  mongodb:",
        `    image: ${service.image}`,
        "    restart: unless-stopped",
        "    ports:",
        `      - \"${service.port}:${service.port}\"`,
        "    volumes:",
        `      - ${projectSlug}_${service.volumeSuffix}:/data/db`,
        "    healthcheck:",
        '      test: ["CMD", "mongosh", "--eval", "db.adminCommand(\'ping\')"]',
        "      interval: 10s",
        "      timeout: 5s",
        "      retries: 5",
      ];
    case "postgresql":
      return [
        "  postgres:",
        `    image: ${service.image}`,
        "    restart: unless-stopped",
        "    environment:",
        `      POSTGRES_DB: ${projectSlug}`,
        "      POSTGRES_USER: app",
        "      POSTGRES_PASSWORD: local_dev_password",
        "    ports:",
        `      - \"${service.port}:${service.port}\"`,
        "    volumes:",
        `      - ${projectSlug}_${service.volumeSuffix}:/var/lib/postgresql/data`,
        "    healthcheck:",
        '      test: ["CMD-SHELL", "pg_isready -U app"]',
        "      interval: 10s",
        "      timeout: 5s",
        "      retries: 5",
      ];
    case "mysql":
      return [
        "  mysql:",
        `    image: ${service.image}`,
        "    restart: unless-stopped",
        "    environment:",
        `      MYSQL_DATABASE: ${projectSlug}`,
        "      MYSQL_USER: app",
        "      MYSQL_PASSWORD: local_dev_password",
        "      MYSQL_ROOT_PASSWORD: local_root_password",
        "    ports:",
        `      - \"${service.port}:${service.port}\"`,
        "    volumes:",
        `      - ${projectSlug}_${service.volumeSuffix}:/var/lib/mysql`,
        "    healthcheck:",
        '      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]',
        "      interval: 10s",
        "      timeout: 5s",
        "      retries: 5",
      ];
    case "redis":
      return [
        "  redis:",
        `    image: ${service.image}`,
        "    restart: unless-stopped",
        "    ports:",
        `      - \"${service.port}:${service.port}\"`,
        "    volumes:",
        `      - ${projectSlug}_${service.volumeSuffix}:/data`,
        "    healthcheck:",
        '      test: ["CMD", "redis-cli", "ping"]',
        "      interval: 10s",
        "      timeout: 5s",
        "      retries: 5",
      ];
  }
}

function slugProjectName(name: string): string {
  return (
    name
      .toLowerCase()
      .replace(/[^a-z0-9]+/gu, "_")
      .replace(/^_+|_+$/gu, "")
      .slice(0, 48) || "app"
  );
}
